#
# This is used by ./rdev.sh to manage the various robotpy packages
#

[params]

parallel = true
cc_launcher = "ccache"
# strip_libpython = true
# macosx_deployment_target = "12"


wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/release"
wpilib_bin_version = "2024.1.1-beta-3"
# wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/development"

# Don't update these artifacts
exclude_artifacts = [
    "opencv-cpp"
]

robotpy_build_req = "<2025.0.0,~=2024.0.0b3"

#
# Subproject configuration
#
# allwpilib-based package versioning is xxxx.x.x.y:
# - x is the upstream version
# - y are specific robotpy patches when we release out of band
#
# Beta releases are always YEAR.0.0bX[.postX]
#

[subprojects."robotpy-wpiutil"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-wpinet"]
min_version = "2024.0.0b2"
roborio = true

[subprojects.pyntcore]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-hal"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-wpimath"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-cscore"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-apriltag"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-wpilib"]
min_version = "2024.0.0b2"
roborio = true

[subprojects."robotpy-halsim-ds-socket"]
min_version = "2024.0.0b2"
roborio = false

[subprojects."robotpy-halsim-ws"]
min_version = "2024.0.0b2"
roborio = false

[subprojects."robotpy-halsim-gui"]
min_version = "2024.0.0b2"
roborio = false
